Repository dusk-network/bls12_381, pull requests merged in 2021-01, with the labels that each got.

#43 Implement/derive Canon for all 'groups' types
  src/fp.rs
  src/fp12.rs
  src/fp2.rs
  src/fp6.rs
  src/g1.rs
  src/g2.rs
Labels: type:feature

#45 G1Affine to/from bytes
  CHANGELOG.md
  Cargo.toml
  src/fp.rs
  src/g1.rs
  src/g2.rs
  src/lib.rs
  src/multiscalar_mul.rs
  src/pairings.rs
  src/scalar.rs
  src/tests/g1_uncompressed_valid_test_vectors.dat
  src/tests/g2_uncompressed_valid_test_vectors.dat
  src/tests/mod.rs
Labels: area:API, team:Core, type:perfomance

#51 Fixes #50 - Incorrect encoding for unchecked bytes
  CHANGELOG.md
  Cargo.toml
  src/g1.rs
  src/g2.rs
Labels: team:Core, type:bug

#53 Canonical v0.5
  CHANGELOG.md
  Cargo.toml
Labels: team:Core
